@startuml
skinparam backgroundColor #FFFFFF
skinparam shadowing true
skinparam roundcorner 10
skinparam defaultFontSize 18
skinparam ArrowThickness 2

skinparam actor {
    BackgroundColor<<User>> #LightGreen
    BorderColor<<User>> Black
}

skinparam participant {
    BackgroundColor #FFFFFF
    BorderColor #000000
    FontColor Black
    ArrowColor Black
}

actor User as U <<User>>
participant "Next Framework" as NextFramework <<Frontend>>
participant FastAPI as FastAPI <<Backend>>
participant SQLite as SQLite <<Backend>>
participant OpenStackSDK as OpenStackSDK <<Backend>>

box "Frontend" #LightGreen
    participant NextFramework
end box

box "Backend" #LightBlue
    participant FastAPI
    participant SQLite
    participant OpenStackSDK
end box

box "OpenStack" #LightSalmon
    participant OpenStackKeystone
    participant OpenStackGlance
    participant OpenStackNova
    participant "New VM Instance" as VMInstance
end box

== Login Process ==
U -> NextFramework: User Login request
NextFramework -> FastAPI: Forward login request
FastAPI -> OpenStackSDK: Request to authenticate
OpenStackSDK -> OpenStackKeystone: OAuth Redirect
OpenStackKeystone -> OpenStackSDK: OAuth Token + User Info
OpenStackSDK -> FastAPI: User Info
FastAPI -> SQLite: Store user info

SQLite -> FastAPI: User info stored
FastAPI -> NextFramework: Login Success
NextFramework -> U: Login Success Notification

== Upload VM Template ==
U -> NextFramework: Button Upload VM Template
NextFramework -> FastAPI: POST upload VM
FastAPI -> SQLite: Store VM template and info
SQLite -> FastAPI: VM template stored
FastAPI -> OpenStackSDK: Upload Image
OpenStackSDK -> OpenStackGlance: Upload Image
OpenStackGlance -> OpenStackSDK: Image ID
OpenStackSDK -> FastAPI: Image ID
FastAPI -> SQLite: Store Image ID
SQLite -> FastAPI: Image ID stored
FastAPI -> NextFramework: Upload Success
NextFramework -> U: Upload Success Notification




== Browsing VM Store ==
U -> NextFramework: Request to browse VM store
NextFramework -> FastAPI: Fetch VM data
FastAPI -> SQLite: Retrieve VM thumbnails & details
SQLite -> FastAPI: Return VM details
FastAPI -> NextFramework: VM Data with thumbnails
NextFramework -> U: Display VMs

== Deploying a VM (Access Verification) ==
U -> NextFramework: Deploy VM request
NextFramework -> FastAPI: Request to deploy VM
FastAPI -> SQLite: Fetch VM template (verify user access)
SQLite -> FastAPI: Return template (with access check)
FastAPI -> OpenStackSDK: Template and other Info
OpenStackSDK -> OpenStackGlance: Image ID
OpenStackGlance -> OpenStackSDK: Image


== Deploying a VM (VM Creation) ==
OpenStackSDK -> OpenStackNova: Image and Parameters
OpenStackNova -> VMInstance: Create
activate VMInstance
VMInstance -> OpenStackNova: Status
OpenStackNova -> OpenStackSDK: VM Instance ID
OpenStackSDK -> FastAPI: VM deployed and running
FastAPI -> NextFramework: Deployment complete
NextFramework -> U: VM Deployment Success

U -> VMInstance: User logs into instance

@enduml
